import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const extensionRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const sourcePath = resolve(extensionRoot, "../server/app/port-candidates.json")
const outputPath = resolve(extensionRoot, "src/generated/portCandidates.ts")
const contract = JSON.parse(readFileSync(sourcePath, "utf8"))

if (
  typeof contract.service !== "string" ||
  !Number.isInteger(contract.protocol_version) ||
  !Array.isArray(contract.ports) ||
  contract.ports.length === 0 ||
  contract.ports.some((port) => !Number.isInteger(port) || port < 1024 || port > 65535) ||
  new Set(contract.ports).size !== contract.ports.length
) {
  throw new Error(`Invalid port contract: ${sourcePath}`)
}

const generated = `// Generated by scripts/generatePortCandidates.mjs. Do not edit.
export const KIBITZER_SERVICE = ${JSON.stringify(contract.service)}
export const KIBITZER_PROTOCOL_VERSION = ${contract.protocol_version}
export const KIBITZER_PORT_CANDIDATES = [${contract.ports.join(", ")}] as const
`

if (process.argv.includes("--check")) {
  const current = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : ""
  if (current !== generated) {
    throw new Error("Generated port candidates are stale. Run npm run ports:generate.")
  }
} else {
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, generated)
}
