#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="$ROOT/apps/menubar/macos/KibitzerMenuBar.swift"
BUILD_DIR="$ROOT/apps/menubar/macos/build"
OUTPUT="$BUILD_DIR/KibitzerMenuBar"
MODULE_CACHE="$BUILD_DIR/module-cache"

if ! command -v swiftc >/dev/null 2>&1; then
  echo "swiftc is required. Install Xcode Command Line Tools, then rerun this script." >&2
  exit 1
fi

mkdir -p "$BUILD_DIR" "$MODULE_CACHE"

# Stamp the binary with version/commit/build time so the menu can show which
# build is actually running (a stale binary is invisible otherwise).
VERSION="$(sed -n 's/^version = "\(.*\)"$/\1/p' "$ROOT/pyproject.toml" | head -n 1)"
[[ -n "$VERSION" ]] || VERSION="unknown"
COMMIT="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || true)"
if [[ -n "$COMMIT" && -n "$(git -C "$ROOT" status --porcelain --untracked-files=no 2>/dev/null)" ]]; then
  COMMIT="${COMMIT}+dirty"
fi
if [[ -n "$COMMIT" ]]; then
  COMMIT_LITERAL="\"$COMMIT\""
else
  COMMIT_LITERAL="nil"
fi
BUILT_AT="$(date '+%Y-%m-%d %H:%M')"
BUILD_INFO_FILE="$BUILD_DIR/BuildInfo.swift"
cat > "$BUILD_INFO_FILE" <<EOF
// Generated by scripts/macos_build_menu_bar.sh — do not edit.
enum MenuBarBuildInfo {
    static let version = "$VERSION"
    static let commit: String? = $COMMIT_LITERAL
    static let builtAt = "$BUILT_AT"
}
EOF

# Multi-file swiftc only allows top-level code in a file named main.swift, so
# compile the source through a main.swift symlink.
MAIN_LINK="$BUILD_DIR/main.swift"
ln -sf "$SOURCE" "$MAIN_LINK"

if ! CLANG_MODULE_CACHE_PATH="$MODULE_CACHE" swiftc \
  "$MAIN_LINK" \
  "$BUILD_INFO_FILE" \
  -D KIBITZER_GENERATED_BUILD_INFO \
  -o "$OUTPUT" \
  -framework AppKit \
  -module-cache-path "$MODULE_CACHE"; then
  echo "Swift build failed." >&2
  echo "If the error mentions an unsupported SDK/compiler mismatch, update or reinstall Xcode Command Line Tools." >&2
  exit 1
fi

echo "Built $OUTPUT"
