#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RAW_DEST="$ROOT/raw/sources/code-files"
WIKI_DEST="$ROOT/wiki/code"

mkdir -p "$RAW_DEST" "$WIKI_DEST"
find "$RAW_DEST" -type f -name '*.md' -delete
find "$WIKI_DEST" -type f -name '*.md' -delete

slugify() {
  echo "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed 's#[/._]#-#g' \
    | sed 's#[^a-z0-9-]#-#g' \
    | sed 's#--*#-#g' \
    | sed 's#^-##; s#-$##'
}

language_for() {
  case "$1" in
    *.py) echo "python" ;;
    *.ts) echo "ts" ;;
    *.tsx) echo "tsx" ;;
    *.mjs) echo "js" ;;
    *.json) echo "json" ;;
    *.yaml|*.yml) echo "yaml" ;;
    *) echo "text" ;;
  esac
}

module_links_for() {
  local rel="$1"
  local links="[[code-map-pages]]"
  case "$rel" in
    apps/server/app/core/*|apps/server/app/schemas.py)
      links="$links [[server-core-pipeline-module]] [[observation-pipeline]]"
      ;;
    apps/server/app/providers/*|configs/*)
      links="$links [[server-provider-boundaries-module]] [[tiered-drift-judging]]"
      ;;
    apps/extension/*)
      links="$links [[extension-background-worker-module]] [[chrome-extension-adapter]]"
      ;;
  esac
  echo "$links"
}

write_source() {
  local rel="$1"
  local abs="$ROOT/$rel"
  [[ -f "$abs" ]] || return 0

  local slug
  slug="$(slugify "$rel")"
  local lang
  lang="$(language_for "$rel")"
  local module_links
  module_links="$(module_links_for "$rel")"

  for out in "$RAW_DEST/$slug.md" "$WIKI_DEST/$slug.md"; do
  {
    printf -- "---\n"
    printf "type: code\n"
    printf "title: \"%s\"\n" "$rel"
    printf "source_path: \"%s\"\n" "$rel"
    printf "generated: true\n"
    printf "related: [code-map-pages]\n"
    printf -- "---\n\n"
    printf "# %s\n\n" "$rel"
    printf "Generated code search source for LLM Wiki. Do not edit this file directly.\n\n"
    printf "Related: %s\n\n" "$module_links"
    printf '```%s\n' "$lang"
    sed 's/```/` ` `/g' "$abs"
    printf '\n```\n'
  } > "$out"
  done
}

while IFS= read -r file; do
  rel="${file#"$ROOT/"}"
  write_source "$rel"
done < <(
  {
    find "$ROOT/apps/server/app" -type f -name '*.py'
    find "$ROOT/apps/extension/src" -type f \( -name '*.ts' -o -name '*.tsx' \)
    find "$ROOT/apps/extension" -maxdepth 1 -type f \( -name 'manifest.json' -o -name 'package.json' -o -name 'build.mjs' \)
    find "$ROOT/configs" -maxdepth 1 -type f \( -name '*.yaml' -o -name '*.yml' \)
    find "$ROOT/scripts" -maxdepth 1 -type f -name '*.py'
  } | sort
)

echo "synced LLM Wiki code sources in $RAW_DEST and $WIKI_DEST"
